# Generated by Django 4.0.4 on 2022-06-06 17:33

from django.conf import settings
from django.db import migrations, models
import rental.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('rental', '0002_alter_books_genre_alter_cds_genre_alter_films_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='films',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Films'},
        ),
        migrations.AddField(
            model_name='books',
            name='deposited_by',
            field=models.ManyToManyField(blank=True, through='rental.UserRentals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cds',
            name='deposited_by',
            field=models.ManyToManyField(blank=True, through='rental.UserRentals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='films',
            name='deposited_by',
            field=models.ManyToManyField(blank=True, through='rental.UserRentals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='books',
            name='ISBN',
            field=models.CharField(max_length=30, unique=True, validators=[rental.models.ISBN_validation]),
        ),
        migrations.AddConstraint(
            model_name='books',
            constraint=models.UniqueConstraint(fields=('title', 'author', 'genre'), name='unique_book'),
        ),
        migrations.AddConstraint(
            model_name='films',
            constraint=models.UniqueConstraint(fields=('title', 'director', 'duration'), name='unique_film'),
        ),
    ]
