# Generated by Django 4.0.4 on 2022-06-06 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_alter_books_options_alter_films_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='deposited_by',
        ),
        migrations.RemoveField(
            model_name='cds',
            name='deposited_by',
        ),
        migrations.RemoveField(
            model_name='films',
            name='deposited_by',
        ),
    ]
